mc_mega_casting_homepage:
    path:     /
    defaults: { _controller: MCMegaCastingBundle:Default:index }


# Offre route
mc_mega_casting_Offre_All:
    path:     /Offre
    defaults: { _controller: MCMegaCastingBundle:Offre:index }
    
mc_mega_casting_Offre_view:
    path:     /Offre/{id_offre}
    defaults: { _controller: MCMegaCastingBundle:Offre:view }
    requirements:
        id_offre: \d+
        
mc_mega_casting_Offre_Add:
    path:     /EspacePro/Offre/Add
    defaults: { _controller: MCMegaCastingBundle:Offre:add }
    requirements:
        type_user: annonceur
    
mc_mega_casting_Offre_Domaine_Metier:
    path:     /Offre/{libelle_domaine}/{libelle_metier}
    defaults: { _controller: MCMegaCastingBundle:Offre:domaine_metier }

mc_mega_casting_Offre_Domaine:
    path:     /Offre/{libelle_domaine}
    defaults: { _controller: MCMegaCastingBundle:Offre:domaine }
    
# Offre Ajax Formulaire
#mc_mega_casting_MetiersByDomaine:
#    path:     /metiers/{id_domaine}
#    defaults: { _controller: MCMegaCastingBundle:Offre:metiers }
#    options:
#        expose: true


# Offre API REST HTTP

offres:
    type:      rest
    resource : MC\MegaCastingBundle\Controller\OffreController 
    

# EspacePro Route
mc_mega_casting_EspacePro:
    path:     /EspacePro
    defaults: { _controller: MCMegaCastingBundle:EspacePro:index }
    
mc_mega_casting_EspacePro_update:
    path:     /EspacePro/modifier/{type_info}
    defaults: { _controller: MCMegaCastingBundle:EspacePro:update }


# EspacePerso Route
mc_mega_casting_EspacePerso:
    path:     /EspacePerso
    defaults: { _controller: MCMegaCastingBundle:EspacePerso:index }
    
mc_mega_casting_EspacePerso_update:
    path:     /EspacePerso/modifier/{type_info}
    defaults: { _controller: MCMegaCastingBundle:EspacePerso:update }


# Artiste Route
mc_mega_casting_Artiste:
    path:     /Artiste
    defaults: { _controller: MCMegaCastingBundle:Artiste:index }
    
mc_mega_casting_Artiste_view:
    path:     /Artiste/{id_artiste}
    defaults: { _controller: MCMegaCastingBundle:Artiste:view }
    requirements:
        id_artiste: \d+

mc_mega_casting_Artiste_Domaine:
    path:     /Artiste/{libelle_domaine}
    defaults: { _controller: MCMegaCastingBundle:Artiste:domaine }
    

# Utilisateur route
mc_mega_casting_register:
    path:     /register/{type_user}
    defaults: { _controller: MCMegaCastingBundle:Security:register }
    requirements:
        type_user: artiste|annonceur
    
mc_mega_casting_user_update:
    path:     /modifier-compte
    defaults: { _controller: MCMegaCastingBundle:Security:update }
    
    

login:
    pattern:   /login
    defaults:  { _controller: MCMegaCastingBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
    