mc_mega_casting_homepage:
    path:     /
    defaults: { _controller: MCMegaCastingBundle:Default:index }


# Offre route
mc_mega_casting_Offre_All:
    path:     /Offre
    defaults: { _controller: MCMegaCastingBundle:Offre:index }
    
mc_mega_casting_Offre_view:
    path:     /Offre/{id_offre}
    defaults: { _controller: MCMegaCastingBundle:Offre:view }
    requirements:
        id_offre: \d+
        
mc_mega_casting_Offre_Add:
    path:     /Offre/Add
    defaults: { _controller: MCMegaCastingBundle:Offre:add }
    
mc_mega_casting_Offre_Domaine_Metier:
    path:     /Offre/{libelle_domaine}/{libelle_metier}
    defaults: { _controller: MCMegaCastingBundle:Offre:domaine_metier }

mc_mega_casting_Offre_Domaine:
    path:     /Offre/{libelle_domaine}
    defaults: { _controller: MCMegaCastingBundle:Offre:domaine }


# EspacePro Route
mc_mega_casting_EspacePro:
    path:     /EspacePro
    defaults: { _controller: MCMegaCastingBundle:EspacePro:index }
    
mc_mega_casting_EspacePro_Register:
    path:     /EspacePro/Register
    defaults: { _controller: MCMegaCastingBundle:EspacePro:register }


# EspacePerso Route
mc_mega_casting_EspacePerso:
    path:     /EspacePerso
    defaults: { _controller: MCMegaCastingBundle:EspacePerso:index }
    
mc_mega_casting_EspacePerso_Login:
    path:     /EspacePerso/login
    defaults: { _controller: MCMegaCastingBundle:EspacePerso:login }
    
mc_mega_casting_EspacePerso_Logout:
    path:     /EspacePerso/logout
    defaults: { _controller: MCMegaCastingBundle:EspacePerso:logout }
    
mc_mega_casting_EspacePerso_Register:
    path:     /EspacePerso/Register
    defaults: { _controller: MCMegaCastingBundle:EspacePerso:register }


# Artiste Route
mc_mega_casting_Artiste:
    path:     /Artiste
    defaults: { _controller: MCMegaCastingBundle:Artiste:index }
    
mc_mega_casting_Artiste_view:
    path:     /Artiste/{id_artiste}
    defaults: { _controller: MCMegaCastingBundle:Artiste:view }
    requirements:
        id_artiste: \d+

mc_mega_casting_Artiste_Domaine:
    path:     /Artiste/{libelle_domaine}
    defaults: { _controller: MCMegaCastingBundle:Artiste:domaine }
    

# Utilisateur route
mc_mega_casting_Utilisateur_Register:
    path:     /Utilisateur/Register/{type_user}
    defaults: { _controller: MCMegaCastingBundle:Utilisateur:add }    
    
    

   