mc_mega_casting:
    resource: "@MCMegaCastingBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_js_routing:
<<<<<<< HEAD
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
=======
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
#REST 
rest : 
  type : rest 
  resource : "routing_rest.yml"
  prefix : /api
>>>>>>> origin/master
