security:
    encoders:
        Symfony\Component\Security\Core\User\User: sha512
        MC\MegaCastingBundle\Entity\Utilisateur: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_ARTISTE, ROLE_ANNONCEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: MC\MegaCastingBundle\Entity\Utilisateur, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: login
                check_path: login_check
                username_parameter: mc_megacastingbundle_utilisateur[username]
                password_parameter: mc_megacastingbundle_utilisateur[password]
            logout:
                path:   logout
                target: /

    access_control:
        - { path: ^/EspacePerso, roles: ROLE_ARTISTE }
        - { path: ^/EspacePro, roles: ROLE_ANNONCEUR }
