security:
    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   ROLE_ADMIN
    
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider:       fos_userbundle
                csrf_provider:  form.csrf_provider
            logout:     ~
            anonymous:  ~
        
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
